config/routes.rb
Rails.application.routes.draw do

  resources :sayings

  root "pages#index"

end

app/models/saying.rb
class Saying < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/controllers/sayings_controller.rb
class SayingsController < ApplicationController

  def index
    @sayings = Saying.all
  end

  def new
    @saying = Saying.new
  end

  def create
    @saying = Saying.new(sayings_params)
    @saying.save
    redirect_to sayings_path
  end

  private

  def sayings_params
    params.require(:saying).permit(:quote)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Turek Family
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
  %nav.navbar.navbar-inverse.navbar-fixed-top{:role=> "navigation"}
    .container-fluid
      .navbar-header
        %a.navbar-brand{:href=> "/"} Turek Fam
        %ul.nav.navbar-nav
          %li
            = link_to "Old Man", sayings_path

  = yield

app/views/pages/index.html.haml
.container

  .jumbotron
    .container
      %h1 The Tureks
      %h2 We're not like other families.

app/views/pages/old-man.html.haml
.container-fluid
  - @om_sayings = ["Oh fist!",
                  "Fisticuffing sack of fisting shelfhead",
                  "No track records, no accountability",
                  "Be part of the solution, not the problem!",
                  "Shorten the distance",
                  "It's not about age, it's about pressure",
                  "It smells like colon wrapped in colon left on a sidewalk in the sun",
                  "Well it's fast Sunday, so boot leather would taste good right now!",
                  "I will slam dunk you into a cave, you recalcitrant pterodactyl",
                  "Go stick your head in the oven and see how long 5 minutes is",
                  "Maximum amounts of Alge Crumpler, Def you!"]
  .row
    .col-md-10.col-md-offset-2
      %h2 Sometimes it's hard to express yourself.  Let the old man help!
  .row.oldman
    .col-md-4.col-md-offset-2
      %img.img-responsive{src:"http://localhost:3000/assets/Old-Man.jpg"}
    .col-md-5
      %h1
        = @om_sayings.sample
  .row.oldmanbutton
    .col-md-2.col-md-offset-5
      =link_to "Is that all you got, old man?", oldman_path

app/views/sayings/index.html.haml
.container-fluid
  .row
    .col-md-10.col-md-offset-2
      %h2 Sometimes it's hard to express yourself.  Let the old man help!
  .row.oldman
    .col-md-4.col-md-offset-2
      = image_tag("Old-Man.jpg")
    .col-md-5
      %h1
        - if @sayings.present?
          = @sayings.sample.quote
  .row.oldmanbutton
    .col-md-2.col-md-offset-2
      =link_to "Is that all you got, old man?", sayings_path, :class => "btn btn-default"
    .col-md-2.col-md-offset-1
      OR
    .old-md-2.col-md-offset-1
      = link_to "Add your own!", new_saying_path, :class => "btn btn-default"

app/views/sayings/new.html.haml
.container-fluid

  = form_for @saying, :html => {:class => 'form-horizontal'} do |f|

    .form-group
      = f.label :quote, :class => "col-md-1 col-md-offset-1 control-label"
      .col-md-9
        = f.text_field :quote, :class => "form-control"

    = f.submit 'It speaks?!?!', :class => "btn btn-primary col-md-offset-6"